/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "npm:kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface ChargerAuth {
  chargerId: number;
  createdAt: Generated<string | null>;
  expiryDate: string | null;
  id: Generated<number | null>;
  idTag: string;
  parentIdTag: string | null;
  status: string;
  updatedAt: Generated<string | null>;
}

export interface ChargerData {
  chargerId: number;
  id: Generated<number | null>;
  meterStart: number | null;
  meterStop: number | null;
  sampledValue: string | null;
  timestamp: Generated<string | null>;
  transactionId: number | null;
}

export interface Chargers {
  createdAt: Generated<string | null>;
  firmwareVersion: string | null;
  id: Generated<number | null>;
  model: string;
  registrationStatus: Generated<string | null>;
  serialNumber: string;
  updatedAt: Generated<string | null>;
  vendor: string;
}

export interface ChargerStatus {
  chargerId: number;
  errorCode: string | null;
  id: Generated<number | null>;
  info: string | null;
  status: string;
  timestamp: Generated<string | null>;
  vendorErrorCode: string | null;
}

export interface ChargerTransactions {
  chargerId: number;
  createdAt: Generated<string | null>;
  id: Generated<number | null>;
  idTag: string;
  meterStart: number | null;
  meterStop: number | null;
  reason: string | null;
  startTime: string;
  status: Generated<string | null>;
  stopTime: string | null;
  transactionId: number;
}

export interface Migrations {
  createdAt: Generated<string | null>;
  id: Generated<number | null>;
  name: string;
}

export interface DB {
  chargerAuth: ChargerAuth;
  chargerData: ChargerData;
  chargers: Chargers;
  chargerStatus: ChargerStatus;
  chargerTransactions: ChargerTransactions;
  migrations: Migrations;
}
