/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "npm:kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface ChargePoints {
  id: Generated<number | null>;
  lastHeartbeat: string | null;
  name: string | null;
  status: Generated<string>;
}

export interface Events {
  chargePointId: number;
  data: string | null;
  eventType: string;
  id: Generated<number | null>;
  timestamp: string;
}

export interface Migrations {
  createdAt: Generated<string | null>;
  id: Generated<number | null>;
  name: string;
}

export interface Transactions {
  chargePointId: number;
  id: Generated<number | null>;
  meterStart: number;
  meterStop: number | null;
  startTime: string;
  status: Generated<string>;
  stopTime: string | null;
}

export interface DB {
  chargePoints: ChargePoints;
  events: Events;
  migrations: Migrations;
  transactions: Transactions;
}
