/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "npm:kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface ChargePoints {
  id: Generated<number | null>;
  last_heartbeat: string | null;
  name: string | null;
  status: Generated<string>;
}

export interface Migrations {
  created_at: Generated<string | null>;
  id: Generated<number | null>;
  name: string;
}

export interface DB {
  charge_points: ChargePoints;
  migrations: Migrations;
}
